version: '3'
services:
  mysql:
    image: mysql/mysql-server:8.0.28
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-file /init-local.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hm_local
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - LANG=C.UTF-8
    volumes:
      - ./docker/init-local.sql:/init-local.sql
    ports:
      - '3306:3306'
  redis:
    image: redis:4-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
  web-api:
    build: .
    restart: unless-stopped
    environment:
      - NODE_ENV=local
      - API_PORT=${API_PORT_LOCAL}
      - WEB_PORT=${WEB_PORT_LOCAL}
    ports:
      - ${API_PORT_LOCAL}:${API_PORT_LOCAL}
      - ${WEB_PORT_LOCAL}:${WEB_PORT_LOCAL}