version: '3'
services:
  mysql:
    image: mysql/mysql-server:8.0.28
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-file /init-local.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hm_local
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - LANG=C.UTF-8
    volumes:
      - ./docker/init-local.sql:/init-local.sql
    ports:
      - '3306:3306'
    healthcheck:
      test: mysql --user=${MYSQL_USER} --password=${MYSQL_ROOT_PASSWORD} ${MYSQL_DATABASE} -e 'select 1';
      interval: 1s
      timeout: 3s
      retries: 30
  redis:
    image: redis:4-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 1s
      timeout: 3s
      retries: 30
  web-api:
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    build: .
    entrypoint: sh -c "cd api ; npm run lint ; npm run test ; cd .. ; npm run test ; npm run lint ; npm run build ; npm run serve:api & npm run serve:web"
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${API_PORT_LOCAL}:${API_PORT_LOCAL}
      - ${WEB_PORT_LOCAL}:${WEB_PORT_LOCAL}
