DROP DATABASE IF EXISTS hm_test;
CREATE DATABASE IF NOT EXISTS hm_test CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
DROP DATABASE IF EXISTS hm_local;
CREATE DATABASE IF NOT EXISTS hm_local CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
